### ISSUE TITLE
Unify product routing

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/ShopApiPlugin#185]
Right now we have two styles of endpoints for products. For example, for product details following routes apply:
 * products/{code}
 * products-by-slug/{slug}

In order to unify them, my proposal is as follows:
 * products/by-code/{code}
 * products/by-slug/{slug}

Rest of endpoints would work similar way, so instead of `taxon-products-by-slug/` we would have `taxon-products/by-slug/`

**Comment by mamazu** [comment]
This looks like a yes. I will try to get to it in the next few days.
However this should then also apply to all product related endpoints like taxons and reviews.


* products/by-code/{code}
* products/by-slug/{slug}
* products/by-code/{code}/reviews
* products/by-slug/{slug}/reviews
* taxon-products/by-code/{taxonCode}
* taxon-products/by-slug/{taxonSlug}

**Comment by mamazu** [comment]
What do you think? @lchrusciel

**Comment by lchrusciel** [comment]
Seems to be ok, I don't have any better idea for now :)
