### ISSUE TITLE
[Bug] Password reset doesn't persist token.

### ISSUE THREAD

**Issue by haltsir** [Sylius/ShopApiPlugin#207]
In `src/Handler/GenerateResetPasswordTokenHandler.php`, a newly generated token is assigned to the `$user` entity, but is not persisted.

**Comment by lchrusciel** [comment]
Did you encounter this problem at your own app? Or did you just suggest it from the code?
The tactician doctrine middleware should flush every change, but on the other hand, the test for this endpoint is not really good https://github.com/Sylius/SyliusShopApiPlugin/blob/master/tests/Controller/CustomerResetPasswordApiTest.php#L19-L46.

**Comment by haltsir** [comment]
I did, yes. Since the feature isn't documented, I explored the API and when requested a password reset, I got the e-mail with a token, but the token wasn't saved to the database.

I haven't tested this on a clean installation.

**Comment by mamazu** [comment]
Well, works with me. Maybe something is overriding the doctrine middleware? Are all the other endpoints working that modify the database?

**Comment by diimpp** [comment]
@mamazu I've exact issue with adding items to cart with current master. Works alright, but result is not persist.

**Comment by diimpp** [comment]
@mamazu Actually just figured it out, you suggestion was on point. `config/packages/league_tactician.yaml` was installed automatically and didn't have doctrine middleware out of the box.

I've imported ShopApi `config.yaml` at `config/packages/_sylius.yaml`, but apparently it gets overridden.
