### ISSUE TITLE
Some of the command constructors missing typehints

### ISSUE THREAD

**Issue by diimpp** [Sylius/ShopApiPlugin#219]
https://github.com/Sylius/SyliusShopApiPlugin/blob/master/src/Command/DropCart.php
while some of them are alright
https://github.com/Sylius/SyliusShopApiPlugin/blob/master/src/Command/AddProductReviewByCode.php

Just an observation in case it was missed.

**Comment by lchrusciel** [comment]
Of course, it is a bug. I have started to use it in a middle of development and didn't found time to introduce it to the whole codebase
