### ISSUE TITLE
Codebase cleanup

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/ShopApiPlugin#238]
We should enforce a few good practices inside the plugin:

- [x]  Add strict types declaration to all classes
- [x]  Remove assert in favour of type hints
- [ ]  Remove redundant doc blocks(for constructor for example)
- [ ]  Replace param docblocks with short syntax

**Comment by mamazu** [comment]
Now this should be updated to:
:heavy_check_mark: Added strict types to classes (I checked with PHPStorm)
:heavy_check_mark: Remove assert in favour of typehints
:black_circle: Remove redundant doc blocks
:black_circle:  Replace param docblocks with short syntax (what ever that means)

**Comment by mamazu** [comment]
What do you mean with the short syntax?

**Comment by lchrusciel** [comment]
For example https://github.com/Sylius/ShopApiPlugin/pull/307/files#diff-b7b599a1c07c6c9a437e7a82bb0086f3R17

It is done anyway ;)

**Comment by mamazu** [comment]
Okay, I already started that but I wasn't sure if its the right one. :+1:
