### ISSUE TITLE
[BUG Report] Customer Checkout

### ISSUE THREAD

**Issue by sdleiw** [Sylius/ShopApiPlugin#243]
Hi, 

I could not checkout as a customer, in the address select page can only submit the form without the email, but then in the complete page there is no customer_id in the sylius_order table, so I cannot complete the checkout, 

can I somehow create a customer in the address step and then link to the order?

**Comment by lchrusciel** [comment]
You would need to extend AdressOrder handler probably

**Comment by mamazu** [comment]
This is fixed in the current version. Please close.
