### ISSUE TITLE
Question creditcard payment?

### ISSUE THREAD

**Issue by antonioperic** [Sylius/ShopApiPlugin#244]
hi @lchrusciel ,
I am not sure what will be the flow if we want to use credit cards for payment. I assume in mobile app user should enter CC info, complete payment and then sent something to API - can you help with this? How to do that exactly?

Thank you.

**Comment by lchrusciel** [comment]
We have provided a custom solution when we have used it. There were two possibilities in our use. Either the token/encrypted cart has been processed by Sylius or Sylius just exposed a returned URL, so the customer could be redirected to some payment provider. But our implementation wasn't too general, so there wasn't any point in sharing it.

**Comment by mamazu** [comment]
For more information please have a look at the ongoing pull request #310
