### ISSUE TITLE
Product Attribute Type Select doesn't properly translate (Sylius 1.1)

### ISSUE THREAD

**Issue by baublet** [Sylius/ShopApiPlugin#260]
Likely related to https://github.com/Sylius/Sylius/pull/8766#issue-144617894

When using the shop API, this bundle does not return product select-type attribute values with their proper translations. It instead returns the unique ID of the translation. For example, the API returns as the attribute's value: `["bfbfe392-8cc8-601f-2da3-12106c1fde98"]`, instead of `["Purple"]`. #

**Comment by baublet** [comment]
## Response Example

`GET localhost:8080/app_dev.php/shop-api/products/test-product?channel=default`

```
{
...
"attributes": [
        {
            "code": "material",
            "name": "Material",
            "value": [
                "1393f36e-1e5d-11e8-9842-0242ac120003"
            ]
        }
    ],
...
}
```

## Expected:

```
{
...
"attributes": [
        {
            "code": "material",
            "name": "Material",
            "value": [
                "Wood"       // Or locale equivalent
            ]
        }
    ],
...
}
```

**Comment by gorkalaucirica** [comment]
@baublet are you working on it?

We have already fixed this in one of our proyects.

I can send a PR

**Comment by baublet** [comment]
Hey @gorkalaucirica, thanks for the reply! I have not yet had time to address this. A PR for this would be excellent.
