### ISSUE TITLE
Create aliases for Factory classes

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/ShopApiPlugin#261]
Right now in case you need to extend factory classes you need to overwrite original class definition in your project to reuse that class via composition.

I suggest creating aliases for all views with their current name, and adding `.default` suffix to existing services. No BC break, and better DX. For example:

```xml
<service id="sylius.shop_api_plugin.factory.product_view_factory.default" class="Sylius\ShopApiPlugin\Factory\ProductViewFactory">
    ...
</service> 
```

```xml
<service id="sylius.shop_api_plugin.factory.product_view_factory" alias="sylius.shop_api_plugin.factory.product_view_factory.default" />
```
WDYT?

I can send a PR

**Comment by lchrusciel** [comment]
For most of the cases overriding should do the job thanks to symfony decorates attribute, but I cannot see any major disadvantage of your proposal, so why not? 

I will be happy to merge it :)

**Comment by mamazu** [comment]
I don't see a use for that. As there are no other services that would use the same service name with a different suffix.

**Comment by mamazu** [comment]
Hm, I just came across this problem and I would say that this is indeed a good idea. Otherwise you need to also override all the usages.

**Comment by mamazu** [comment]
So, @lchrusciel just pointed out that if you decorate a service this will change the service itself.
```xml
<service id="vendor.shop_api_plugin.factory.product_view_factory"
         class="App\Services\Factory\DecoratingFactory"
         decorates="sylius.shop_api_plugin.factory.product_view_factory">
    <service type="service" id="sylius.shop_api_plugin.factory.product_view_factory.inner" />
</service>
```

Then the `sylius.shop_api_plugin.factory.product_view_factory` will point to the `DecoratingFactory`.
