### ISSUE TITLE
Plugin does not work with disabled shop API

### ISSUE THREAD

**Issue by bitbager** [Sylius/ShopApiPlugin#264]
This plugin has a strong dependency on Sylius shop API in config. If someone wants to disable the default Sylius Shop API by removing the bundle dependency from Kernel, he will get an error about unsupported `sylius_shop` config.

**Comment by lchrusciel** [comment]
Can you provide more details on this problem? I have tested this plugin with shop turned off, and it seems to work fine. I will try to cover this with tests in https://github.com/Sylius/SyliusShopApiPlugin/pull/271

**Comment by lchrusciel** [comment]
Now, it will break the shop for sure. We need to resolve this problem: https://github.com/Sylius/ShopApiPlugin/blob/master/src/Resources/config/services.xml#L67

**Comment by tophsic** [comment]
I use this bundle too with shop turned off. Without any problem… until now.

**Comment by mamazu** [comment]
What is the problem now?

**Comment by tophsic** [comment]
My english so bad :smile: I did not find any problem yet!

**Comment by mamazu** [comment]
Well that is great. :) This issue is still relevant. I don't know how important it is to maintain compatibility with the Shop integration of Sylius.

**Comment by tophsic** [comment]
Well I was wrong. I had trouble removing `ShopBundle` in my project `bundles.php` file. I did not have error mentioned in description. I missed `sylius.context.cart.session_and_channel_based` in`CompositeCartContext`. The effect was that all my orders prices were not recalculated.

I think issue title is confusing. I would rename it in "ShopApiBundle does not work if ShopBundle is disabled"

**Comment by mamazu** [comment]
Well this issue should remind us to remove the ShopBundle from the dependencies of this project in order to ensure that this is really a headless plugin.

**Comment by lchrusciel** [comment]
Ok, this one will be important. ShopBundle is not usable with current ShopApiPlugin implementation, due to CartContext and also a problem with recalculation. Therefore, we shouldn't require it in bundles. 

Conflicting ShopApiPlugin implementation with default is ok, but not when we still need ShopBundle in bundles list.

**Comment by mamazu** [comment]
We should put that into the `README.md` so that everyone who downloads it can see it.

**Comment by lchrusciel** [comment]
Mentioned in #492
