### ISSUE TITLE
Add support for Sylius v1.2.0

### ISSUE THREAD

**Issue by pamil** [Sylius/ShopApiPlugin#278]

**Comment by witrin** [comment]
@pamil Is there a schedule for this?

**Comment by lchrusciel** [comment]
I'm still looking for some time to spend on this, but feel free to help me with it :)

**Comment by witrin** [comment]
@lchrusciel Can you give me some hints what is needed to be done?

**Comment by lchrusciel** [comment]
Mostly this #281 should be merged, but there is some internal problem with translations. Also, we should run Sylius test suite to check if whole Sylius is working correctly.

**Comment by witrin** [comment]
@lchrusciel Many of the errors were caused by `nelmio/alice` update. But there are still some open. Should I better post intermediate results or only final results?

**Comment by lchrusciel** [comment]
If you only can, please share your fixes :) Feel free to push them directly to my branch

**Comment by witrin** [comment]
@lchrusciel Sorry I meant push not post :D ...

**Comment by witrin** [comment]
@lchrusciel 

1. JSON matcher does not working anymore.
2. Undefined index did not came up locally.
3. I  did not checked the failures right now.

**Comment by witrin** [comment]
@lchrusciel @pamil Can't tell what's needed here https://github.com/Lakion/ApiTestCase/pull/125. Everything else is done! Could you please review?

**Comment by lchrusciel** [comment]
I will verify it ASAP :)
