### ISSUE TITLE
Unify routing naming

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/ShopApiPlugin#300]
![image](https://user-images.githubusercontent.com/6213903/44410024-cfb6a900-a563-11e8-8319-3b840aa3f602.png)

We should have one, a consistent prefix for all ShopAPI related routes.

**Comment by mamazu** [comment]
Do you mean the names or the routes itself?

**Comment by lchrusciel** [comment]
yes

**Comment by pamil** [comment]
`sylius_shop_api` would be the preferred one IMO.
