### ISSUE TITLE
Conflict between shop and shop-api for password reset

### ISSUE THREAD

**Issue by ChafikHadjAbdouRazack** [Sylius/ShopApiPlugin#313]
Conflict between shop and shop-api for password reset

**Comment by lchrusciel** [comment]
Which version of ShopApi are you using? It should not be a problem since: https://github.com/Sylius/ShopApiPlugin/pull/302

**Comment by ChafikHadjAbdouRazack** [comment]
@lchrusciel i used 1.0 version

**Comment by lchrusciel** [comment]
@ChafikHadjAbdouRazack can you dump the `composer show -v` command? The issue should be fixed in v1.0.0-beta.21

**Comment by ChafikHadjAbdouRazack** [comment]
@lchrusciel i have version  v1.0.0-beta.20

**Comment by lchrusciel** [comment]
composer update should do the trick then

**Comment by ChafikHadjAbdouRazack** [comment]
@lchrusciel thanks
