### ISSUE TITLE
Add typechecking with phpstan

### ISSUE THREAD

**Issue by mamazu** [Sylius/ShopApiPlugin#320]
Currently when running phpstan with the highest standards the API produces about 120 errors.

**Comment by mamazu** [comment]
**Problem**
For level 5 we have the problem that Sylius uses the classes from the `Core`-namespace but the repositories for example return the objects from the component.

```
 ------ ------------------------------------------------------------------------------------------------------------------- 
  Line   src/Factory/ListProductViewFactory.php                                                                             
 ------ ------------------------------------------------------------------------------------------------------------------- 
  81     Parameter #1 $product of method Sylius\ShopApiPlugin\Factory\ListProductViewFactory::createWithVariants() expects  
         Sylius\Component\Core\Model\ProductInterface, Sylius\Component\Product\Model\ProductInterface given.               
 ------ ------------------------------------------------------------------------------------------------------------------- 
```
for example here:
https://github.com/Sylius/ShopApiPlugin/blob/d4e22dc338d38e57c9a011054631757531c1df83/src/Factory/ListProductViewFactory.php#L81

`$associatedProduct` Is from the Compontent but the method expects one from the Core. This is best practice in Sylius the problem is that those classes don't inherit from another which makes sense, because the components should be modular. But how do we deal with that?

**Suggested fix**
We ignore those errors as long as they are in the same class. Someone/I would need to create a regex that ignores if the parser complains about classes from the component bundle if the class with the same name is used from the core bundle.

**Comment by lchrusciel** [comment]
How many of them are reported already? Is it possible to use a low-cost solution and ignore some of the errors, or do we need to create full regex? The problem exists in Sylius itself, so I would wait until we decide what to do about it internally in the first place. There were some issues about it already. Also, can we just cast the parameter to expected value with adding 

```
/** @var Core\ProductIntreface $associatedProduct
```

just before the loop?

For short term solution, I would just cast variable.

**Comment by mamazu** [comment]
Well there is no easy fix for this. The ignored errors in phpstan are always regular expressions. And I know that this is a problem with the Sylius internal code as well. But Sylius chooses to not check the codestyle as strictly. (it's still on phpstan level 1). It's not a very huge issue as there are just about 14 errors reported due to it.

The for the moment easiest fix would be to ignore the error (the regex should not be too complicated). Or we litter the code with a lot of assertions that check for the right class.
However, the solution you suggested is not viable because if the method as a PHP return type (hard coded in php) then phpstan will ignore docblocks that try to convince it otherwise.

**Comment by lchrusciel** [comment]
So let's ignore them for now

**Comment by mamazu** [comment]
Okay, until then this discussion can be closed, for now.
