### ISSUE TITLE
Resurrect UPGRADE.md

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/ShopApiPlugin#340]
We need to document changes such as https://github.com/Sylius/ShopApiPlugin/pull/339

**Comment by mamazu** [comment]
An `UPGRADE.md` already exists but I don't know which version it upgrades to because we don't have a tagged version.

**Comment by lchrusciel** [comment]
My fault. We need to resurrect this file then.

**Comment by lchrusciel** [comment]
I need to process this problem and figure it out. Not sure what will be the best option right now

**Comment by mamazu** [comment]
I think for now that we should just list all the changes and then we can still add Headings for the versions later on. What do you think?

**Comment by mamazu** [comment]
I think this issue can be closes as we are now taking care of the read me one merge request at a time. :D
