### ISSUE TITLE
Remove channelCode from request payloads

### ISSUE THREAD

**Issue by bartoszpietrzak1994** [Sylius/ShopApiPlugin#345]
It's no use passing channelCode in payload when it's now attached to every URL as a request parameter.

**Comment by mamazu** [comment]
@stefandoorn We have the same "problem". The thing is all endpoints in the current version of the API have the channel code in the URL. All end points, no a small route still resists. The `login_check` route still is based on the default Symfony authentication and requires the `HostnameBasedChannelResolver`

Our current fix is to redirect the `shop-api/{channelCode}/login_check` to `/shop-api/login_check` on a different host name. It's not the best fix but this way we don't need to fumble with the Symfony authentication.

**Comment by mamazu** [comment]
I think this issue can be closed as the ShopApi is now fully converted or what do you think @bartoszpietrzak1994
