### ISSUE TITLE
PHP 7.2 compatible and API Platform

### ISSUE THREAD

**Issue by pierre-H** [Sylius/ShopApiPlugin#346]
Hello,

Thank you to Sylius team for your great work !

Is the ShopApiPlugin compatible with PHP 7.2 ?

Will it be a version using API Platform which is becoming a standard for creating API with Symfony ?

Thank you again !

**Comment by mamazu** [comment]
Currently my organization is running running Sylius and its ShopApi with php 7.2 without any problems.

**Comment by mamazu** [comment]
I guess this issue can be closed as well.
