### ISSUE TITLE
Missing properties provided by the client result in many cases in exceptions

### ISSUE THREAD

**Issue by healerz** [Sylius/ShopApiPlugin#353]
After playing a bit with the api, i recognized that requests often end in an exception if i don't provide all mandatory params.
E.g. the address action in the checkout process, if i don't provide the shipping address it ends in the following exception:
> { "code": 500, "message": "Argument 1 passed to Sylius\\ShopApiPlugin\\Model\\Address::createFromArray() must be of the type array, null given, called in /srv/sylius/vendor/sylius/shop-api-plugin/src/Controller/Checkout/AddressAction.php on line 33" .....

Personally, i think cases like this should result in a validation exception always and return a status code in the 4xx range back to the client. Preferably a 422, but a 400 is ok also.

If "we" would stick to the command bus pattern and create non type hinted Request objects first, and validate them afterwards, this wouldn't happen.

To illustrate what i mean, i created a work in progress PR (I haven't adjusted / enhanced the tests yet):
https://github.com/Sylius/ShopApiPlugin/pull/352

Before i put in more effort, i would like to know what you guys think :)

**Comment by mamazu** [comment]
#424 is related to that issue a little as it also doeson't handle the error gracefully.
