### ISSUE TITLE
override verification email

### ISSUE THREAD

**Issue by aayaresko** [Sylius/ShopApiPlugin#358]
hello. how can I override the 'verification.html.twig' template? putting ShopApiPlugin/Email/verification.html.twig under templates/bundles does not solve the issue.

**Comment by mamazu** [comment]
In the `app/Resources/ShopApiPlugin/Email/verification.html.twig`

**Comment by aayaresko** [comment]
doesn't work. "sylius/sylius": "~1.3.0",

**Comment by aayaresko** [comment]
still using the old template, overriding has no effect.

**Comment by aayaresko** [comment]
created a file 'ShopApiPlugin:Email:verification.html.twig' and pasted the file into the 'templates', the issue seems to be gone, but the file name... that definitely is not the way to override templates.

**Comment by mamazu** [comment]
You could also override the config and then define a different template.

**Comment by aayaresko** [comment]
could you lease send me a link where I can read about that or with an example

**Comment by aayaresko** [comment]
found it, no worries

**Comment by Tyryshkinm** [comment]
@aayaresko 

> found it

It is very good, but can you understand how you solve the problem? Or maybe shared this magic link with an example?
