### ISSUE TITLE
register endpoint does not store email_verification_token

### ISSUE THREAD

**Issue by aayaresko** [Sylius/ShopApiPlugin#359]
after a user gets registered via shop-api/register endpoint the 'email_verification_token' field of the user is null. the user cannot confirm his email.

**Comment by aayaresko** [comment]
found what's causing it. another config for tactician overrides the one from the SyliusShopApi

**Comment by mamazu** [comment]
Ah, but that is not a Sylius issue/plugin but something specific to your instance?

**Comment by aayaresko** [comment]
well, with symfony4 we have a case when league_tactician.yaml from config/packages overrides the one for SyliusShopApi.

**Comment by aayaresko** [comment]
I made copy-pasted the config from SyliusShopApi to the config/packages
