### ISSUE TITLE
swagger documentation

### ISSUE THREAD

**Issue by dlobato** [Sylius/ShopApiPlugin#373]
Hi,

First of all, thank you for all your work! Great contribution to sylius ecosystem.

I've just started to use the bundle, and I plan to connect to the shop api through a javascript client.
I'm testing swagger-client, which creates a client out of the swagger.yml documentation. So far seems very promissing.

I've seen that the document is currently not valid (according to this: https://apidevtools.org/swagger-parser/online/) and I've also seen that there's some operationIds duplicated (for instance, productCatalog).

What's the plan to maintaint this document? I've seen #251 and I was wondering about the current state.

**Comment by mamazu** [comment]
Well the state is that when people pull request something I will mention to update the API documentation if they don't include it. :D

About the ticket you mentioned, the issue reporter didn't follow through with his implementation and I couldn't get api platform working so currently there is nobody working on that. Feel free to change that.

About the swagger editor. Working with it in the browser it is terribly slow with this huge document and quite a large chunk of work to check all the request objects again. But again feel free to update it. If you need any help, just ask away.

Good luck with that.

**Comment by dlobato** [comment]
So currently the swagger.yml is manually maintained, right?
I guess that for the time being I might try to fix it, but sure this would be difficult to keep up to date.

What about something like NelmioApiDocBundle to generate the file? Of course, it would need some effort to annotate things. I've just done a simple test and out of the box it generates a swagger.yml with all the paths plus all path parameters. I'm not yet familiar with the code, but maybe it make sense on the long run to use php swagger annotations. (sure it doesn't solve the fact that it still needs to be maintained).

**Comment by stefandoorn** [comment]
If you can automate the generation, then maybe a bot can submit PR's on the Swagger docs as soon as another PR has been merged. Or it can submit commits to PR's that adjust the schema, but that one might be harder to do.

**Comment by dlobato** [comment]
After a closer look, NelmioApiDocBundle uses php annotations to generate the swagger file. So far I see that there's no php annotations anywhere on the code, so I'm guessing there's some sort of coding style policy against it.

I think that I'll try to stick with the current approach and maybe think on how to improve with other solution.

**Comment by mamazu** [comment]
The reason why we don't have any (or very few annotations) is because most of them are just the method most annotations don't provide any value as they just reflect the method signature with their type hints. If you need them for the documentation do ahead and add one.

**Comment by dlobato** [comment]
For the time being this fixes the docs: https://github.com/Sylius/ShopApiPlugin/pull/376

**Comment by mamazu** [comment]
Can this issue be closed?

**Comment by dlobato** [comment]
Sure

**Comment by mamazu** [comment]
You can close this by clicking on the close button underneath the comment field. :)
