### ISSUE TITLE
Order editable during payment

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/ShopApiPlugin#381]
May be critical.

An order become new and so block adding/removing items when the checkout goes to complete.
But during the payment selected process people are still able to edit order and so by default allow people to pay only a partial part of the order.

Is there something wrong in my usage of the API ?

Actual example :
When someone click on a payment it open the page of any payment system, the price is fixed. Order is still in cart state as the person haven't pay.
He modify order, he's allowed since the order isn't in new state.
He pay on the payment tab.

**Comment by stefandoorn** [comment]
Isn't what @vasilvestre is hinting to is an order status 'paying' (or something similar) that kind of 'locks' the order from adjustments that affect pricing? Not sure that's solely for API plugin then, might be benefical for Sylius in general.

**Comment by vasilvestre** [comment]
I think adding or removing items should be blocked while it's in payment_selected. But the cart could go back to another state if someone reload page at checkout or product list.
I'm not sure but this seem a problem imo

**Comment by vasilvestre** [comment]
Database entity payment is updated when I add an item so the control fail. I'm really feeling like there's a critical problem

**Comment by vasilvestre** [comment]
After a try on sylius demo, I see that they modify checkout_state to complete right after choosing payment method even without paying. So checkout is complete and payment is in "awaiting payment" state.
