### ISSUE TITLE
Checkout context command and handlers

### ISSUE THREAD

**Issue by tomaszfelczyk** [Sylius/ShopApiPlugin#391]
Hi,
During revision and extending of ChooseShippingMethod process I found some restrictions that can be probably solved.

To add delivery at point ability to sylius i need to extend Shipment model with delivery point details (cause it hard depended on shipping method attached to shipment). I also extend ShippingMethod model with "delivery at point" flag which means that the method requires delivery point details.
After creating DeliveryPoint view and factory, extending ShippingMethodView and ShipmentView and decorating ShippingMethodViewFactory ShipmentViewFactory I was able to deliver data to frontend app.

The problem starts when I want to handle extended ChooseShippingMethod Command with DeliveryPoint model:

1. All Checkout Handlers repeat:
```
$cart = $this->orderRepository->findOneBy(['tokenValue' => $chooseShippingMethod->orderToken()]);
Assert::notNull($cart, 'Cart has not been found.');
$stateMachine = $this->stateMachineFactory->get($cart, OrderCheckoutTransitions::GRAPH);
```

2. If I want to attach some data to $shipment i need to write own Handler and copy all code inside. (Decoration couldn't work - handler apply transaction)

3. EgibilityChecker
`Assert::true($this->eligibilityChecker->isEligible($shipment, $shippingMethod), 'Given shipment is not eligible for provided shipping method.');`
shouldnt be in TRANSITION_SELECT_SHIPPING gruard?

Solution:

1. Create OrderTokenAwareInterface with:
`public function orderToken()`
2. Use (implement) this interface in all checkout commands like ChooseShippingMethod
3. Create StateMachineContextHandlerInterface with:
`public function getStateMachineGraph()`
`public function getStateMachineTransition()`
4. Implement StateMachineContextHandlerInterface in all checkout handlers like ChooseShippingMethod:
`public function getStateMachineGraph(){
    return OrderCheckoutTransitions::GRAPH;
}`
`public function getStateMachineTransition(){
    return OrderCheckoutTransitions::TRANSITION_SELECT_SHIPPING;
}`

5. Create new CommandHandlerMiddleware:
```
// example
public function execute($command, callable $next)
        {
        $commandName = $this->commandNameExtractor->extract($command);
        $handler = $this->handlerLocator->getHandlerForCommand($commandName);
        $methodName = $this->methodNameInflector->inflect($command, $handler);

        $model = null;
        // This "if" statement is to much focus on Order and can be more generic but it's only for present idea
        if($command instanceof OrderTokenAwareInterface){
            $model = = $this->orderRepository->findOneBy(['tokenValue' => $chooseShippingMethod->orderToken()]);
        }

        if($model && $handler instanceof StateMachineContextHandlerInterface){
            $stateMachine = $this->stateMachineFactory->get($model, $handler->getStateMachineGraph());
            $result = $handler->hande($command, $stateMachine);
            $stateMachine->apply($handler->getStateMachineTransition());
            return $result;
        }

        // is_callable is used here instead of method_exists, as method_exists
        // will fail when given a handler that relies on __call.
        if (!is_callable([$handler, $methodName])) {
            throw CanNotInvokeHandlerException::forCommand(
                $command,
                "Method '{$methodName}' does not exist on handler"
            );
        }

        return $handler->{$methodName}($command);
}
```

6. Then ChooseShippingMethodHandler will be:
```
    public function handle(ChooseShippingMethod $chooseShippingMethod, StateMachineInterface $stateMachine)
    {
        $cart = $stateMachine->getObject();

        /** @var ShippingMethodInterface $shippingMethod */
        $shippingMethod = $this->shippingMethodRepository->findOneBy(['code' => $chooseShippingMethod->shippingMethod()]);
        Assert::notNull($shippingMethod, 'Shipping method has not been found');

        Assert::true(isset($cart->getShipments()[$chooseShippingMethod->shipmentIdentifier()]), 'Can not find shipment with given identifier.');

        $shipment = $cart->getShipments()[$chooseShippingMethod->shipmentIdentifier()];
        Assert::true($this->eligibilityChecker->isEligible($shipment, $shippingMethod), 'Given shipment is not eligible for provided shipping method.');

        $shipment->setMethod($shippingMethod);
    }
```

7. Then i can create own NewChooseShippingMethodHandler that decorates ChooseShippingMethodHandler:

```
 public function handle(ChooseShippingMethod $chooseShippingMethod, StateMachineInterface $stateMachine)
{
        $this->baseHandler->handle($chooseShippingMethod, $stateMachine);
        $cart = $stateMachine->getObject();
        $shipment = $cart->getShipments()[$chooseShippingMethod->shipmentIdentifier()];
        $shippingMethod = $this->shippingMethodRepository->findOneBy(['code' => $chooseShippingMethod->shippingMethod()]);

        if($shippingMethod->isDeliveryAtPoint()){
            Assert::notNull($chooseShippingMethod->getDeliveryPoint(), 'error message');
        }

        $shipment->setDeliveryPoint($chooseShippingMethod->getDeliveryPoint());
}
```

**Comment by mamazu** [comment]
In the problem point number 3 you mentioned that the eligibility checks should be done in the guard instead of an external service that is explicitly called. This would mean that you would need to change the GUI in the back-end as well, because without this no shipping method can be selected.

But this sounds reasonable. When the responsibility of checking if the transition is doable, is inside the state machine. Do you have an idea how this could work?
