### ISSUE TITLE
PUT Checkout Address is not persisting Order

### ISSUE THREAD

**Issue by mikeymclellan** [Sylius/ShopApiPlugin#403]
When I `PUT /shop-api/checkout/.../address` the Handler adds the addresses to the Order and applies the state change, however, the Order is never flushed so changes aren't persisted. The responce code is `204`.

As part of my debugging I added an `em->flush()` after the `$stateMachine->apply(OrderCheckoutTransitions::TRANSITION_ADDRESS)` and everything works as expected. 

I feel like I'm missing something, as none of the other Handlers seem to `flush()` either.  🤔

**Comment by mamazu** [comment]
You might not know, but the flushing is done in the middleware of the CommandHandler. This is done after the Handler Logic is executed. It could be that the tactician bundle is not correctly configured.

**Comment by mikeymclellan** [comment]
Okay great to know that it should be working. I'll double check my tactician config.

**Comment by mikeymclellan** [comment]
Ahh this was totally my issue. I was missing the 
```
  - { resource: "@ShopApiPlugin/Resources/config/app/config.yml" }
  - { resource: "@ShopApiPlugin/Resources/config/app/sylius_mailer.yml" }

**Comment by mikeymclellan** [comment]
Ahh this was totally my issue 🤦‍♂️, thanks for your help. I was missing the:

```
# app/config/config.yml

imports:
    # ...
  - { resource: "@ShopApiPlugin/Resources/config/app/config.yml" }
  - { resource: "@ShopApiPlugin/Resources/config/app/sylius_mailer.yml" }
```

**Comment by mamazu** [comment]
Sounds great. Thanks for sharing the solution as well. Now we have an issue to point people with the same solution.
