### ISSUE TITLE
Promotion based on customer_group rule is not applied

### ISSUE THREAD

**Issue by tophsic** [Sylius/ShopApiPlugin#406]
I got a promotion based on `customer_group` rule. I saw that `customer_id` is attached to an order only at checktout complete step. So `$subject->getCustomer()` is null before this step and promotion can not be applied.

At this point, I wish this kind of promotion could be applied before checkout step.

Besides, the promotion is not even applied at checktout step.

What is normal and what needs to be fixed?

I can work on a PR but maybe need some help on how to fix this. I will begin to write failing test.

**Comment by mamazu** [comment]
I have never looked at the promotion behaviour as we haven't yet implemented this in our system. But this seems like a bug.
A pull request for the fix would be great. If you have any questions, feel free to ask.

**Comment by tophsic** [comment]
I prefered to look why  customer id is not set directly on cart if user is logged in when calling `POST /shop_api/<channel_code>/carts`. Is there any reason why customer_id is not set at this step?

**Comment by tophsic** [comment]
If it is ok to add customer id on cart creation if user is logged. I would firstly change `Tests\Sylius\ShopApiPlugin\Controller\Cart\CartPickupApiTest::it_only_creates_one_cart_if_user_is_logged_in` test in:

```php
    /**
     * @test
     */
    public function it_only_creates_one_cart_and_link_cart_to_user_if_user_is_logged_in(): void
    {
        $this->loadFixturesFromFiles(['shop.yml', 'customer.yml']);

        $this->logInUser('oliver@queen.com', '123password');

        $this->client->request('POST', '/shop-api/WEB_GB/carts', [], [], static::CONTENT_TYPE_HEADER);
        $response = $this->client->getResponse();
        $this->assertResponseCode($response, Response::HTTP_CREATED);

        /** @var OrderRepositoryInterface $orderRepository */
        $orderRepository = $this->get('sylius.repository.order');
        $orders = $orderRepository->findAll();

        $this->assertCount(1, $orders, 'Only one cart should be created');

        $order = current($orders);

        $this->assertNotNull($order->getCustomer());
    }
```

**Comment by mamazu** [comment]
This should be working out of the box I think. But I don't think renaming the test is a good idea. Because if a test case has an and in it, you are checking two things in one test. This could be split up into two tests.

**Comment by tophsic** [comment]
I thought about splitting in two tests but the only thing is I have to add an assertion. So I prefer your renaming proposition.

**Comment by tophsic** [comment]
I got some problem to declare customer group and promotion rule fixtures.

```
Sylius\Component\Promotion\Model\PromotionRule:
    customer_group_rule:
        type: "customer_group"
        promotion: "@group_promotion"
        configuration:
            group_code: "@premium"

Sylius\Component\Customer\Model\CustomerGroup:
    premium:
        code: "premium"
        name: "Premium customers"
```

Results in this in database:

```
mysql> select * from sylius_promotion_rule where type = 'customer_group';
+----+--------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id | promotion_id | type           | configuration                                                                                                                                                        |
+----+--------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  6 |           34 | customer_group | a:1:{s:10:"group_code";O:45:"Sylius\Component\Customer\Model\CustomerGroup":3:{s:5:" * id";i:4;s:7:" * code";s:7:"premium";s:7:" * name";s:17:"Premium customers";}} |
+----+--------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

How can I get customer group id instead of serializing the object?

**Comment by tophsic** [comment]
I was tired because we do not need a fixture reference but only customer group code!

**Comment by mamazu** [comment]
It could be that the fixtures doesn't support setting the promotion's customer group. But I also think that this is the wrong place to implement this. We need to recalculate the cart every time it is modified (e.g. PutToCart, RemoveFromCart etc.)

**Comment by lchrusciel** [comment]
This is a bug. We are assigning logged in customer only on the last step, which means customer promotion can be applied only on cart complete, while it is important to show this discount as soon as possible. 

The proper fix is to provide a logic so that each time customer will log in, and we will assign the current cart to him. What is more, we should also trigger cart recalculation logic, and remove the listener, which recalculates a cart for each request.

**Comment by lchrusciel** [comment]
Done in #488
