### ISSUE TITLE
Impossible to install the Shop Api

### ISSUE THREAD

**Issue by MEDYN4** [Sylius/ShopApiPlugin#410]
Hello, I'm trying to install the plugin to my sylius (1.4.1) project.
I run the command `composer require sylius/shop-api-plugin:^1.0@beta` but i get this error 

[InvalidArgumentException]
  Could not find package sylius/shop-api-plugin in a version matching 1.0@beta

When I don't specify the version I get that : 

[InvalidArgumentException]
  Could not find a version of package sylius/shop-api-plugin matching your minimum-stability (stable). Require it wit
  h an explicit version constraint allowing its desired stability.

How can I install a working version to my project?

**Comment by mamazu** [comment]
You can install the master branch (`composer require sylius/shop-api-plugin dev-master`) or lower your minimum stability (not recommended) and install the dev version.

**Comment by MEDYN4** [comment]
Thanks! I installed the dev-master
It's working fine

**Comment by mamazu** [comment]
Glad I could help.
