### ISSUE TITLE
Composer version is not the latest

### ISSUE THREAD

**Issue by Prometee** [Sylius/ShopApiPlugin#431]
The latest downloaded version is base on the alias name of the composer package, so the latest version which `composer` will install is the `v1.0.0-beta.9` and not `v1.0.0-beta.21`. The packagist page is pointing the latest version but if you look to the packagist badge into the `README.md` it show us what will be the latest installable version of this package (`v1.0.0-beta.9`).

So there is 2 solutions :
 - update all alias between `v1.0.0-beta.1` to `v1.0.0-beta.9` and add a zero before the final number
 - create a new alias pointing to an alias like `v1.0.xx-beta` where `xx` will be incremented

**Comment by mamazu** [comment]
That is indeed bad. Sounds like composer doesn't like this beta version tagging.

I think changing the release tags would just be a fix and will become a problem when there is a three digit beta release (I hope we can get a stable version out before that).

**Comment by CSchulz** [comment]
IMO it is just an issue with the README.md. I haven't installed the plugin to verify, but if you select on the right side a different version the dependency tree is updated but the README.md preview keeps the same.

**Comment by mamazu** [comment]
Correct. This is only a README issue as composer still recognizes it as the most recent version when using `composer require`. I have removed it in this #459 pull request to avoid confusion.
