### ISSUE TITLE
Address model is not being validated at Checkout\AddressAction step

### ISSUE THREAD

**Issue by diimpp** [Sylius/ShopApiPlugin#433]
Controller validates [`Request\Checkout\AddressOrderRequest` ](https://github.com/Sylius/ShopApiPlugin/blob/master/src/Controller/Checkout/AddressAction.php#L44), which keeps billing/shipping address as array, therefore `Model\Address` validation rules are not applied.

If initialized `Model\Address` will be added to `AddressOrderRequest`, then those models can be validated by association by current controller without any change anywhere else.

P.S. I'm basing my finding on older plugin version, but seems to be the case with current version as well.

**Comment by mamazu** [comment]
Thank you for reporting this issue. You are correct the conversion from the raw request data (array) to the Address entity is done in the `getCommand` method which is called after the validation has finished.

**Comment by mamazu** [comment]
This has been done in the merge request #453
