### ISSUE TITLE
Translation missing for sylius.shop_api.product.configurable

### ISSUE THREAD

**Issue by Prometee** [Sylius/ShopApiPlugin#434]
During the creation of a cart I get this error message :

```
{
    "code": 400,
    "message": "Validation failed",
    "errors": [
        {
            "productCode": [
                "sylius.shop_api.product.configurable"
            ]
        }
    ]
} 
```

And the translation is not available.

**Comment by mamazu** [comment]
This meas that you are trying to add a product that has to be configured but no configuration is given or the other way around. The product is not configurable but you gave it a variant.

**Comment by Prometee** [comment]
I understand the meaning of the error but there is many translations missing

**Comment by mamazu** [comment]
In the shop api the messages are not translated. This would require some kind of locale for every request just for displaying.

**Comment by Prometee** [comment]
It should be translated anyway, because the API can retrieve the default local of the Sylius app.
And it contribute to the comprehension of own the API is working for someone who don't know how the API is coded.

In my own case, I have to read the different `Action` `Handler` `routing` files and sometime read the outdated Swagger doc to know how to add my own API endpoints and how to work with this Plugin.

So getting good explained messages could contribute to a larger adoption of this plugin and maybe more contributors I think.

**Comment by mamazu** [comment]
Well translating the messages has it's advantages and disadvantages. For example it is much easier to check for this generic string than a translated message. For example we use the API and translate them in the client.
