### ISSUE TITLE
AddressOrderHandler missing company/phone

### ISSUE THREAD

**Issue by hashnz** [Sylius/ShopApiPlugin#435]
The call to add an address from the cart doesn't handle the company or phoneNumber fields, just wondering if this is intentional, if not I can submit a PR

https://github.com/Sylius/ShopApiPlugin/blob/master/src/Handler/Cart/AddressOrderHandler.php

**Comment by mamazu** [comment]
This is a missing feature. Please submit a pull request but leave those parameters optional I'd say.

**Comment by hashnz** [comment]
Here you go: https://github.com/Sylius/ShopApiPlugin/pull/442

**Comment by mamazu** [comment]
Closed by merging #442
