### ISSUE TITLE
Taxes applied to a province code are not taken into account

### ISSUE THREAD

**Issue by Prometee** [Sylius/ShopApiPlugin#440]
The `AddressOrderHandler` never set the `provinceCode` so the tax calculator never know what is the correct tax to applied to the order. Also the `Address`es are no validated so no errors occurred ( #433 ).

I fix this problem decorating `AddressOrderHandler` and adding the missing fields mapping :
 - `provinceCode`
 - `company`
 - `phoneNumber`

This is maybe a critical bug like the one on Promotion Customer Group ( #406 ) because it could put some accounting bugs to the shop owners.

**Comment by GSadee** [comment]
Thank you for reporting the issue. It is also associated with #435
Would you like to open a PR with the fix?

**Comment by Prometee** [comment]
I will, but at the moment I have to focus on the staging phase of my project, but I really would like to contribute to this ;)

**Comment by mamazu** [comment]
There is currently a pull request in the pipeline that would probably fix that: #453

**Comment by mamazu** [comment]
Solved by #453 I'd say.
