### ISSUE TITLE
[FEATURE] Allow devs to update the mapped data (*Request to *Handler)

### ISSUE THREAD

**Issue by Prometee** [Sylius/ShopApiPlugin#441]
If we can alter the mapped data for exemple here :

https://github.com/Sylius/ShopApiPlugin/blob/6e25aa869dd58d624c1f9bbf746704909c1986a2/src/Handler/Cart/AddressOrderHandler.php#L48-L68

We can add or remove mapped fields more easily than rewritting all this class by decorating it.

Maybe we can add some `Mapper` class which handle this behaviour.

The result would be :
```
/** @var AddressInterface $shippingAddress */
$shippingAddress = $this->addressMapper->map($order, $addressOrder->shippingAddress());

/** @var AddressInterface $billingAddress */
$billingAddress = $this->addressMapper->map($order, $addressOrder->billingAddress());
```

What do you think about this ?

**Comment by mamazu** [comment]
This has been done in the most recent merge request: #453
