### ISSUE TITLE
Resources are out of date

### ISSUE THREAD

**Issue by CSchulz** [Sylius/ShopApiPlugin#445]
I want to try out this plugin and noticed the release and documentation is out dated f.e. the login process is not existing in the swagger.
The authentication is referred from the readme.md but the file is not existing anymore (seems to be splitted up into different tests).

Are there any plans to fix this?

**Comment by mamazu** [comment]
Thanks for reporting this problem. I think you are referring to the outdated version of the readme which is still based on symfony version 3. I will try and fix this.
