### ISSUE TITLE
Non-existent service sylius_shop_api_plugin.command_bus

### ISSUE THREAD

**Issue by seriousTom** [Sylius/ShopApiPlugin#456]
Hello I tried to install dev-master version of shopApiPlugin into my sylius project but when I try to launch my project I get this error:

The service "sylius.shop_api_plugin.controller.address_book.create_address_action" has a dependency on a non-existent service "sylius_shop_api_plugin.command_bus".

It works fine with beta version. But head-dev said to install dev-master version.

**Comment by mamazu** [comment]
Do you have the Symfony Messenger bundle installed?

**Comment by seriousTom** [comment]
I didn't install that package myself unless it was installed with some other bundles. Here is my composer.json:
`{
    "keywords": ["symfony", "symfony2", "sylius", "distribution", "ecommerce", "cart", "shopping"],
    "type": "project",
    "license": "proprietary",
    "homepage": "https://sylius.com",
    "authors": [
        {
            "name": "Paweł Jędrzejewski"
        },
        {
            "name": "Sylius project"
        },
        {
            "name": "Community contributions"
        }
    ],
    "require": {
        "php": "^7.2",
        "lexik/jwt-authentication-bundle": "^2.6",
        "nelmio/cors-bundle": "^1.5",
        "sylius/shop-api-plugin": "^1.0@beta",
        "sylius/sylius": "~1.5.0@rc",
        "symfony/dotenv": "^4.2",
        "symfony/flex": "^1.2"
    },
    "require-dev": {
        "behat/behat": "^3.4",
        "behat/mink": "^1.7@dev",
        "behat/mink-browserkit-driver": "^1.3",
        "behat/mink-extension": "^2.2",
        "behat/mink-selenium2-driver": "^1.3",
        "friends-of-behat/page-object-extension": "^0.3",
        "friends-of-behat/suite-settings-extension": "^1.0",
        "friends-of-behat/symfony-extension": "^2.0",
        "friends-of-behat/variadic-extension": "^1.1",
        "lakion/mink-debug-extension": "^1.2.3",
        "lchrusciel/api-test-case": "^3.0",
        "phpspec/phpspec": "^5.0",
        "phpunit/phpunit": "^6.5",
        "sensiolabs/security-checker": "^5.0",
        "stripe/stripe-php": "^6.28",
        "sylius-labs/coding-standard": "^2.0",
        "symfony/browser-kit": "^3.4|^4.1",
        "symfony/debug-bundle": "^3.4|^4.1",
        "symfony/intl": "^3.4|^4.1",
        "symfony/maker-bundle": "^1.11",
        "symfony/web-profiler-bundle": "^3.4|^4.1",
        "symfony/web-server-bundle": "^3.4|^4.1"
    },
    "prefer-stable": true,
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        },
        "classmap": ["src/Kernel.php"]
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ],
        "post-create-project-cmd": [
            "@php bin/console sylius:inform-about-gus",
            "@php bin/console sylius:show-available-plugins --ansi"
        ]
    },
    "config": {
        "platform": {
            "php": "7.2"
        },
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony": {
            "allow-contrib": false
        },
        "branch-alias": {
            "dev-master": "1.5-dev"
        }
    }
}
`

Although I see that something with "messenger" exists in composer.lock file.
https://gyazo.com/1123033f8eacdffd88bfb7f35a7e04a0

**Comment by mamazu** [comment]
If you don't have this configuration copy this into the `src/Resources/config/app/config.yml` or if you have a newer version (4 or greater) of Symofony `config/shop_api.yml`

```yml
framework:
    messenger:
        buses:
            sylius_shop_api_plugin.command_bus:
                middleware:
                    - doctrine_transaction
```

**Comment by seriousTom** [comment]
Now I am getting another error - 'An exception has been thrown during the rendering of a template ("Sylius was not able to figure out the current cart.").'

**Comment by mamazu** [comment]
This is normal. When installing the shop API the front-end doesn't work anymore. There is already a pull request for that. Until then you can either disable the shop front or remove the cart indicator from the templates.

**Comment by seriousTom** [comment]
Okay, I understand. Thanks for the help

**Comment by mamazu** [comment]
You're welcome. For more information feel free to follow the pull request #454
