### ISSUE TITLE
How to add additional attribute to response?

### ISSUE THREAD

**Issue by seriousTom** [Sylius/ShopApiPlugin#461]
Hello,

I added additional attribute 'maxQuantityPerOrder' to ProductEntity and I want to see it`s value in the response.  As know I need to modify ProductViewFactory.php. To modify it I use service decoration.

config/services.yaml:
```
    App\Factory\ShopAPI\ModifiedProductViewFactory:
        decorates: sylius.shop_api_plugin.factory.product_view_factory
        arguments:
            $productViewFactory: '@App\Factory\ShopAPI\ModifiedProductViewFactory.inner'

```

src/Factory/ShopAPI\ModifiedProductViewFactory.php:
```php
namespace App\Factory\ShopAPI;

use Sylius\Component\Core\Model\ChannelInterface;
use Sylius\Component\Core\Model\ProductInterface;
use Sylius\ShopApiPlugin\Factory\ProductViewFactory;
use Sylius\ShopApiPlugin\Factory\ProductViewFactoryInterface;
use Sylius\ShopApiPlugin\View\ProductView;

class ModifiedProductViewFactory implements ProductViewFactoryInterface
{
    private $productViewFactory;

    public function __construct(ProductViewFactory $productViewFactory)
    {
        $this->productViewFactory = $productViewFactory;
    }

    public function create(ProductInterface $product, ChannelInterface $channel, string $locale): ProductView
    {
        $productView = $this->productViewFactory->create($product, $channel, $locale);
        
        $productView->max_quantity_per_order = $product->getMaxQuantityPerOrder();
        
        return $productView;
    }
}
```

I thought it would be enough, but I don`t see new attribute in api response. I am calling this url: /shop-api/products-by-slug/test-product?channel=US_WEB

I tried to use dd function in ShowProductDetailsBySlugAction controller and I noticed that my new attribute disappears after $this->viewHandler->handle call.

Max quantity per order is missing in this case:
`
dd($this->viewHandler->handle(View::create($this->productCatalog->findOneBySlug(
                $request->attributes->get('slug'),
                $request->query->get('channel'),
                $request->query->get('locale')
            ), Response::HTTP_OK)));
`

I can see max quantity per order in this case:
`
dd(View::create($this->productCatalog->findOneBySlug(
                $request->attributes->get('slug'),
                $request->query->get('channel'),
                $request->query->get('locale')
            ), Response::HTTP_OK))
`

So what I am missing or what it would be the best approach to add new attributes to repsonse?

**Comment by mamazu** [comment]
You also need to tell the Serializer to use expose this attribute as there is a custom Serialization rule for the product. You can find the config [here](https://github.com/Sylius/ShopApiPlugin/blob/master/src/Resources/config/serializer/Product/PageView.yml).

**Comment by seriousTom** [comment]
Thanks, this is what I was missing. And it also needs to add niew property in ProductView.php file

**Comment by mamazu** [comment]
Correct.
