### ISSUE TITLE
Autowiring

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/ShopApiPlugin#510]
Hello,

I would like to know if it is possible to autowire the service of ShopApiPlugin please

**Comment by lchrusciel** [comment]
The issue discussed in our slack: https://sylius-devs.slack.com/archives/C3EGDG9LY/p1565334806249600

Long story short: You can use autowire features with ShopApiPlugin. We could add aliases to interfaces used in this project, to make it even easier.
