### ISSUE TITLE
shop-api/login

### ISSUE THREAD

**Issue by mathieudureisseix** [Sylius/ShopApiPlugin#511]
Hi, do we have to implement login controller for jwt because i can t find any routes for it.
Thanks for this good plugin.
Mathieu

**Comment by lchrusciel** [comment]
No, it should be supported out-of-box. Are you using RC version?

**Comment by mathieudureisseix** [comment]
Hi Ichrusciel, thanks for your answer. I had just to create the route and everything worked. It is ok now :)
