### ISSUE TITLE
Channel as parameter

### ISSUE THREAD

**Issue by antonioperic** [Sylius/ShopApiPlugin#513]
Suggestion:
It will be very nice to have the option to send a channel as a parameter. This is API so supplying different devices with different settings is not something that is rarely.

**Comment by mamazu** [comment]
True. Channels are still a big topic in the development of shop api. I would suggest to reword the ticket for better documentation of how channels can be extracted in shop api. As far as I know you can register your own classes to determine the channel all by yourself.

**Comment by antonioperic** [comment]
@mamazu that will be nice, if we don't have that out of the box

**Comment by lchrusciel** [comment]
@antonioperic this feature should work with different hostnames out-of-the-box. Similar to default Sylius. But this should be documented

**Comment by antonioperic** [comment]
@lchrusciel i know, but most APIs will have one hostname 
different hostnames works out of the box

**Comment by mamazu** [comment]
Is fixed by #514. At least the documentation bit.
