### ISSUE TITLE
Customer id is not registered when cart is created

### ISSUE THREAD

**Issue by mathieudureisseix** [Sylius/ShopApiPlugin#516]
Hi, customer id is not set in Oder when cart is created.
I use JWT.
Best regards

**Comment by mathieudureisseix** [comment]
that's fine with the dev-master.
Thanks for this very useful bundle !

**Comment by lchrusciel** [comment]
Hey, thanks for the kind words.

It was fixed in #488 and is part of RC version :) 

Have a nice day!
