### ISSUE TITLE
Installing shop API 1.0rc with Sylius 1.5.3

### ISSUE THREAD

**Issue by flindblom-ohmy** [Sylius/ShopApiPlugin#517]
Hey all,

So I have the API installed and working (mostly) on my main project, but I'm running into some issues that I wanted to ask about, and to be certain that it's an issue with the API and not something that is unique to me I'm doing a clean install of Sylius and the API. (the install on the main project was made by a colleague of mine, so I'm going through this process for the first time) 

However, at this point I can't even get the shop API to work on a fresh install of Sylius, and that raises a few questions about the installation procedure.

> Before installing SyliusShopApiPlugin, you should disable all SyliusShopBundle's dependencies. You cannot use these packages together.

I have no idea what this means or how to do it, maybe explain this a little better in the readme? SyliusShopBundle is loaded in `config/bundles.php` but the above line refers to its dependencies? What dependencies are those? How do I even figure that out?

> Run composer require sylius/shop-api-plugin and, when asked if you want to execute the Flex recipe, answer 'Yes'.

I don't get any question about a Flex recipe in this step. Is that something that I can/should run manually if it doesn't happen?

So, following all instructions in the README, ignoring the bit about NelmioCorsBundle because that is not something that I have installed, loading any page after the shop API has been installed throws the following error:

```The service "sylius.listener.cart_blamer" has a dependency on a non-existent service "sylius_shop_api_plugin.command_bus".```

To reproduce:
composer create-project sylius/sylius MyFirstShop
cd MyFirstShop
Edit .env to fix database credentials
php bin/console sylius:install
yarn install
yarn gulp
composer require sylius/shop-api-plugin
follow the install steps in the shop API README
php bin/console server:start
open http://127.0.0.1:8000

Expected result: Sylius home page appears
Actual result: Exception `The service "sylius.listener.cart_blamer" has a dependency on a non-existent service "sylius_shop_api_plugin.command_bus".`

**Comment by mamazu** [comment]
When running the console does the service show up?
`bin/console debug:container`

**Comment by mamazu** [comment]
To address your other questions:
Yes, the documentation on the ShopApi is still quite poor. As we don't have any flex recepies for the API this part of the docs are quite misleading but there is already a ticket for it.

The information about the fact that the default Sylius Frontend (SyliusShopBundle) is not compatible with the current implementation of ShopApi might also be outdated (I'd have to check that) but if you want to use your system headless anyways this shouldn't be a problem.

About the missing service itself, this should be generated by the Symfony Messenger Bus. If it doesn't you might have forgotten to include the plugin's config into your app or the configuration differs from the default.

**Comment by flindblom-ohmy** [comment]
Thanks for your reply!

I can't run `debug:container`, fails with the same error.

I've been instructed to focus on other parts of the project so I'm going to have to get back to this later, can't do any more digging right now, sorry.

**Comment by mamazu** [comment]
I will try to reproduce it.

**Comment by mamazu** [comment]
I can't reproduce it.

**Comment by flindblom-ohmy** [comment]
Thanks for giving it a shot @mamazu ! Do you still have the clean install of just Sylius and the shop API? Any chance you could zip the config folder and send it to me so I can diff it against mine?

**Comment by mamazu** [comment]
Sure, I will do that this evening.

**Comment by mamazu** [comment]
[config.zip](https://github.com/Sylius/ShopApiPlugin/files/3541164/config.zip)
There you go

**Comment by flindblom-ohmy** [comment]
Fantastic! Thank you!
