### ISSUE TITLE
Totals items include promotion but should not

### ISSUE THREAD

**Issue by alexander-schranz** [Sylius/ShopApiPlugin#521]
If I have a cart with items in value of `60 EUR` and a coupon code with `5 EUR` the totals of items are false e.g.:

```diff
{
  total: 5500,
-  items: 5500, // current
+  items: 6000, // expected
  taxes: 0,
  shipping: 0,
  promotion: -500,
}
```

**Comment by mamazu** [comment]
Promotions in Sylius are handled that way. When adding a cart discount this discount get distributed across all items. This is indeed a little misleading but hard to reverse in my opinon. Maybe we should use the "raw" item price and not the discounted one.

**Comment by alexander-schranz** [comment]
@mamazu oh I see can be closed then as I think we should do the same as sylius does.

**Comment by mamazu** [comment]
Yes, agreed. It also threw us off when we first looked at the order overview in Sylius.
