### ISSUE TITLE
Retrieve JSON Response instead of templates

### ISSUE THREAD

**Issue by tudorradubarbu** [Sylius/ShopApiPlugin#523]
I disabled the ShopBundle from my application.
Calling the API with a simple get `/shop-api/products/by-code/cod001` still gives me an error trying to find a template instead of a JSON Response?

> Unable to find template vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views

Which are the dependencies that need to be disabled so it will work?

**Comment by mamazu** [comment]
It depends on the header (aka, the accepted content types) if you just request it from the browser it will try to return a template because the browser also accepts html.

For reference you can have a look at the [API Tests](https://github.com/Sylius/ShopApiPlugin/blob/master/tests/Controller/JsonApiTestCase.php)

**Comment by tudorradubarbu** [comment]
Thank you @mamazu for the response.
Of course, I already added the correct headers (I hope) but the requests were made with Postman. Can this be a problem?

I have both `Content-Type` and `Accept` set to `application/json`

**Comment by tudorradubarbu** [comment]
Found this:

Inside the `fos_rest.yaml` file. the order is this:

```
    format_listener:
        rules:
            - { path: '^/shop-api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/api/.*', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

```
I don't know why but if you move the shop-api line it will go to html response. Does it make any sense?

**Comment by mamazu** [comment]
Yes the order is correct the ShopApi should only return json.
