### ISSUE TITLE
Outdated swagger doc 

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/ShopApiPlugin#532]
https://app.swaggerhub.com/apis/Sylius/sylius-shop-api/1.0.0 should be updated

**Comment by mamazu** [comment]
Is there any way I can access this an do it?

**Comment by alexander-schranz** [comment]
Could maybe done with the swagger registry-api in a CI job: https://app.swaggerhub.com/apis/swagger-hub/registry-api/1.0.47#/APIs/saveDefinition

**Comment by mamazu** [comment]
@lchrusciel Did you find the credentials?

**Comment by lchrusciel** [comment]
Yes, it should be up-to-date at this moment. Next thing is to automate this process
