### ISSUE TITLE
500 error when registering with exist email address

### ISSUE THREAD

**Issue by alexander-schranz** [Sylius/ShopApiPlugin#533]
When registering with exist email address it should return a 400 status code and not a server side error.

**Comment by mamazu** [comment]
There is a validation for it. Can you check why the `ShopUserDoesNotExistValidator` doesn't add a violation to the list?

**Comment by adrianmarte** [comment]
@alexander-schranz I can not reproduce this issue:

```
{
    "code": 400,
    "message": "Validation failed",
    "errors": {
        "email": [
            "This email is already used."
        ]
    }
}
```


HTTP Status Code is also "400 Bad Request"

**Comment by mamazu** [comment]
Sounds like it works as it is supposed to. Please provide a test case where it fails.
