### ISSUE TITLE
Missing swagger docs for verify-account

### ISSUE THREAD

**Issue by alexander-schranz** [Sylius/ShopApiPlugin#540]
The verify-account seems currently not be documented in the [swagger.yml](https://github.com/Sylius/ShopApiPlugin/blob/bed256ec1cb09cd799546b8b6529a20baf1c14a8/doc/swagger.yml)

**Comment by mamazu** [comment]
@kortwotze will take care of it

**Comment by mamazu** [comment]
Will be merged with #532
