### ISSUE TITLE
Updating a customer without a birthday sets the birthday to the current dat

### ISSUE THREAD

**Issue by nnatter** [Sylius/ShopApiPlugin#544]
When the `birthday` property is omitted (or not set) on a PUT request to the `/me` endpoint, the birthday of the current customer is set to the current date.

The `UpdateCustomerRequest` class declares the `birthday` class-property as nullable, therefore I assume that it should be possible to omit the `birthday` property from this request (eg. if the customer does not want to specify his birthday).
https://github.com/Sylius/ShopApiPlugin/blob/master/src/Request/Customer/UpdateCustomerRequest.php#L25

This behaviour happens because the `UpdateCustomerHandler` constructs a new `DateTimeImmutable` object with the `birthday` property of the `UpdateCustomerRequest`. If this property is null, the constructed `DateTimeImmutable` object will contain the current date.
https://github.com/Sylius/ShopApiPlugin/blob/master/src/Handler/Customer/UpdateCustomerHandler.php#L31

**Comment by mamazu** [comment]
This looks like a bug. Besides the fact that the request class doesn't return a datetime immutable anyways. This looks like a missing typecheck on the command.
