### ISSUE TITLE
Bumping phpstan level up

### ISSUE THREAD

**Issue by mamazu** [Sylius/ShopApiPlugin#545]
Related to #320.

Currently there are still some very odd type descriptions floating around the project which I would love to detect with phpstan. However, currently Sylius' interface and class stucture with bundles create an issue with phpstan.

This could be fixed with a special regular expression so that phpstan can be as strict as it wants without interfering with the Sylius package structure.

**Comment by lchrusciel** [comment]
Solved by #550
