### ISSUE TITLE
Use squash for merging pull requests

### ISSUE THREAD

**Issue by CSchulz** [Sylius/ShopApiPlugin#565]
The git history of master looks a little bit messy, I want to suggest to use squash when merging pull requests to get a clean straight forward history for the master branch.

More details here:

https://help.github.com/en/articles/about-pull-request-merges#squash-and-merge-your-pull-request-commits

**Comment by lchrusciel** [comment]
Thanks a lot for the suggetion. For sure I should take a closer look into commit messages in this repo, so merge requests will not appear for example.

Nevertheless, we want to keep the history of people's commits, so squashing them into master is no go (at least for now). The same approach is used atm in main Sylius repo. However, I will take this feedback and discuss it internally with the rest of CoreTeam.
