### ISSUE TITLE
Bad response when trying to add address

### ISSUE THREAD

**Issue by matik955** [Sylius/ShopApiPlugin#569]
When trying to add address not beeing logged response is: 
```
"code":500,"message":"Argument 1 passed to Sylius\\Component\\Core\\Factory\\AddressFactory::createForCustomer() must implement interface Sylius\\Component\\Core\\Model\\CustomerInterface, null given 
```

It should return status code 401 for example.

**Comment by mamazu** [comment]
This is probably due to #462

**Comment by lchrusciel** [comment]
These endpoints should be hidden behind the firewall. They don't have any sense without it.

**Comment by mamazu** [comment]
True.

**Comment by Amr3zzat** [comment]
I think Address book in only should be behind the firewall in the routes true?

I have just added  access control rule to fix this issue.
in security.yaml
`   access_control:`
`        - { path: "%sylius_shop_api.security.regex%/address-book", role: ROLE_USER}
`

**Comment by mamazu** [comment]
Yes.

**Comment by Amr3zzat** [comment]
@mamazu It should be added to theme readme? Should I create PR with it or there is a better fix?

**Comment by mamazu** [comment]
The best way to fix this is indeed in the routes to protect them in the `security.yml`. Theoretically this should also include the profile routes (eg. /me) This should also be documented in the swagger file which is partly is.

**Comment by mamazu** [comment]
But if you could create a merge request to fix this issue this would be great.
