### ISSUE TITLE
Update customer birthday issue

### ISSUE THREAD

**Issue by matik955** [Sylius/ShopApiPlugin#572]
When trying to update customer with new birthday got error: 
```
Argument 2 passed to JMS\\Serializer\\Handler\\DateHandler::serializeDateTime() must be an instance of DateTime, instance of DateTimeImmutable given
```
No matter what birthday date is set, even the one received from GET /me.

**Comment by mamazu** [comment]
Could not reproduce the bug. Do you have a serialization file that defines how the customer is serialized?

**Comment by matik955** [comment]
No. I didn't have serialization file for customer

**Comment by mamazu** [comment]
Can you maybe post the stack trace of the call? But the GET request for this route works only the POST is a problem?

**Comment by matik955** [comment]
The error appear when decorate customer view factory class. Yes GET /me works but PUT returns error

**Comment by mamazu** [comment]
How does the decoration look?

**Comment by matik955** [comment]
As shown in the cookbook

**Comment by mamazu** [comment]
Hm, and you are not overriding the property with a new value?

**Comment by matik955** [comment]
No, I did not

**Comment by mamazu** [comment]
Can you run the phpunit test for the update endpoint and share the result?

**Comment by matik955** [comment]
Fixed. Thanks
