### ISSUE TITLE
More verbose error messages on denied state changes during checkout

### ISSUE THREAD

**Issue by TiMESPLiNTER** [Sylius/ShopApiPlugin#574]
Currently if I want to complete an order and I haven't gone through defining a payment method all I get when calling `PUT /checkout/{cartToken}/complete` is:

```
{
    "code": 500,
    "message": "Order with {cartToken} token cannot be completed."
}
```

it would be very helpful to have a more verbose error message and maybe another code. As `500` somehow implies that there is a server error and somewhere you should be able to find a stacktrace or at least log entry.

A message like:

> Order with {cartToken} token cannot be completed. Please set a payment method first.

would be way clearer.

**Comment by mamazu** [comment]
Yes, aggregated. Optimally this would be solved with validations and therefore return an error code of 400 but in general this should be improved.
