### ISSUE TITLE
/shop-api/orders endpoints locale is tied to underling orders locale, not request locale

### ISSUE THREAD

**Issue by diimpp** [Sylius/ShopApiPlugin#576]
`/shop-api/orders` endpoints output should be linked to request locale or default locale in channel, if no locale is provided.

Right now orders list will be returned in each orders locale, meaning this api output can be in multiple locales at once.

**Comment by mamazu** [comment]
This is indeed a very strange behaviour but this makes sense. The order data is displayed as it is received. The problem with unifying the language is also what if the product does not have a specific locale? Is it not showing in the list?

**Comment by lchrusciel** [comment]
This is the expected and default behavior of Sylius. Placed order should be displayed in the locale it was placed.

**Comment by diimpp** [comment]
Okay, clothing then, please re-open if still a problem.
