### ISSUE TITLE
[BUG] Gender Field needs validation update user details

### ISSUE THREAD

**Issue by Amr3zzat** [Sylius/ShopApiPlugin#614]
When Sending gender field in "Updates currently logged in users details." End Point ,
It returns 500 when sending more than one character , It should return 400, It needs validation on gender field length.

<img width="798" alt="Screen Shot 2019-12-27 at 3 53 41 PM" src="https://user-images.githubusercontent.com/31932378/71519636-125b6480-28c1-11ea-8c1f-e0eaf2391957.png">

**Comment by Yasser-G** [comment]
also it need to be clear what are acceptable letters that represents `gender` value

**Comment by Amr3zzat** [comment]
@Yasser-G  I did that in my PR

**Comment by mamazu** [comment]
Merged.
