### ISSUE TITLE
[BUG] Missing validation during choosing cart payment method

### ISSUE THREAD

**Issue by maxmishyn** [Sylius/ShopApiPlugin#650]
Example: Lets say we have Method_a and Method_b in the Sylius. But only Method_a is allowed for the channel.

We call [get] /checkout/XXXXXXX/payment and receive Method_a as the only available option. What is correct.

Then we [put] /checkout/XXXXXXX/payment/0 with the body: {"method": "Method_b"}  ( .._b not .._a)

And it works. Method_b becomes payment method for our order what should not happen.

So there should be some validation for this situation.

**Comment by mamazu** [comment]
To be fair. Payment is something that is not integrated very well with this API. But you are correct that this should not be possible.
