### ISSUE TITLE
Invalid handler service "sylius.shop_api_plugin.handler.set_default_address_handler": bus "sylius_shop_api_plugin.command_bus" specified on the tag "messenger.message_handler" does not exist (known ones are: "messenger.bus.default").

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/ShopApiPlugin#652]
Once I run **composer require sylius/shop-api-plugin** command , it showing as 
**Invalid handler service "sylius.shop_api_plugin.handler.set_default_address_handler": bus "sylius_shop_api_plugin.command_bus" specified on the tag "messenger.message_handler" does not exist (known ones are: "messenger.bus.default").**

<img width="1440" alt="Screen Shot 2020-06-03 at 1 22 25 PM" src="https://user-images.githubusercontent.com/20614311/83610666-6fa8bf80-a59d-11ea-8504-e74f00f797eb.png">
<img width="1440" alt="Screen Shot 2020-06-03 at 1 22 38 PM" src="https://user-images.githubusercontent.com/20614311/83610675-746d7380-a59d-11ea-81bc-e44248a080b2.png">

Please guid me to fix this issue

**Comment by mamazu** [comment]
Did you import the service defintions as described in the `README.md`:
```yml
- { resource: "@SyliusShopApiPlugin/Resources/config/app/config.yml" }
```

**Comment by kaushi5054** [comment]
yes I did @mamazu

**Comment by mamazu** [comment]
Hm, can you try to remove the cache.

**Comment by kaushi5054** [comment]
Hi @mamazu, it works  once I clear cash and re installed it again, removing configuration (what I did early) and SyliusShopBundle, this time I works fine, 

without clearing cash even I did same step again it didn't works

thank you

**Comment by illestomas** [comment]
I have the same issue with fresh sylius installation.
Clearing the cache didn't help.
