### ISSUE TITLE
[DOC] How to use payment system ?

### ISSUE THREAD

**Issue by pierre-H** [Sylius/ShopApiPlugin#653]
Hello,

First, thank you for your great work !

Is it possible to have a documentation on how to use a Sylius payment plugin with the ShopApi Plugin ?

Thank you in advance !

**Comment by mamazu** [comment]
Well, there is no standard way of handling the payment method. You just create a new endpoint something like `/pay` and handle the payments there. The standard best pratices for API extensions are documented here:
https://github.com/Sylius/ShopApiPlugin/blob/master/doc/Cookbook.md#extending-shop-api

**Comment by pierre-H** [comment]
Ok. Thank you !
