### ISSUE TITLE
sylius_shop_api_change_password route missing in v1.0.0

### ISSUE THREAD

**Issue by pierre-H** [Sylius/ShopApiPlugin#654]
Hello,

I just want to alert you that the route `sylius_shop_api_change_password` is missing in the 1.0.0 version.
You can check by downloading the [zip file](https://github.com/Sylius/ShopApiPlugin/releases/tag/v1.0.0) of it in the file `src/Resources/config/routing/customer.yml`.

Problem  : this version [Swagger doc](https://app.swaggerhub.com/apis/Sylius/sylius-shop-api/1.0.0#/users/changePassword) indicates that the route exists.

Thank you !

**Comment by mamazu** [comment]
Yeah, this is a problem. We are considering releasing 1.1 for some time now. So then ti should be fixed.
I don't know how the version of the compiled swagger doc is getting there but I guess this is the master probably.

**Comment by Emilvooo** [comment]
I added the route myself, but the validation errors are only in the default locale language. Have you guys also taken that into account for the 1.1 release?

**Comment by mamazu** [comment]
Well version 1.1 is out. I don't know how or where the error messages are translated. I think this is part of Symfony and using the default locale if not specified otherwise.
Version 1.1 should also include a fix for setting locales as far as I remember so just try it out.

**Comment by Emilvooo** [comment]
Its being translated trough the validations translations. So when change-password action is being called, the request data will be validated. I will try 1.1 out! Thx :)
