### ISSUE TITLE
The service "security.authentication.provider.guard.sylius_shop_api" has a dependency on a non-existent service "lexik_jwt_authentication.jwt_token_authenticator".

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/ShopApiPlugin#656]
Hi,

I have installed shop_api in my project and once I run the admin panel it's showing error as 

`The service "security.authentication.provider.guard.sylius_shop_api" has a dependency on a non-existent service "lexik_jwt_authentication.jwt_token_authenticator".`

can you help me to resolve it?

**Comment by mamazu** [comment]
This is probably due to the fact that the JWT plugin is not set up properly. Can you check that it is installed.

**Comment by kaushi5054** [comment]
installation went ok @mamazu , please have look on the attachment. 
I will try again to do it again 
<img width="999" alt="Screen Shot 2020-06-29 at 3 15 56 PM" src="https://user-images.githubusercontent.com/20614311/85995432-d645bf80-ba1b-11ea-9745-49b10e39cf15.png">

**Comment by mamazu** [comment]
Did you also set up the package as described in step 3 in the README?

**Comment by kaushi5054** [comment]
Yes I did it first time, remove cash and the code level changers and did it again it works fine, in first time I sow **nelmio/NelmioCorsBundle** is there so I did that changers also. but the second time it wasn't and it works fine. I think issue with the **nelmio/NelmioCorsBundle** :(

**Comment by mamazu** [comment]
Very strange. If you find out what it is feel free to reopen the issue.
