### ISSUE TITLE
[HELP] How to edit the existing API and  add a new Api

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/ShopApiPlugin#660]
HI,

Please help me to add new API and theta do the modification in existing API. I couldn't find any documentation related to this. Should  I try it same as **sylius** like exporting controllers and etc? Can you Please guide me to do it

Thank you!!

**Comment by mamazu** [comment]
Welcome to the project, sadly documentation on this project is not up to the Sylius Standard. What we have is this cookbook: [doc/Cookbook.md](https://github.com/Sylius/ShopApiPlugin/blob/master/doc/Cookbook.) This will describe how it works and give you some ideas on how to extend it.

**Comment by kaushi5054** [comment]
Thank you @mamazu , I already checked this link and unfortunately it's not available (404) :( :( :(

<img width="1439" alt="Screen Shot 2020-07-01 at 12 53 39 PM" src="https://user-images.githubusercontent.com/20614311/86215350-1cc12880-bb9a-11ea-92bc-36734cc58cb2.png">

**Comment by mamazu** [comment]
Fixed it. Try again

**Comment by kaushi5054** [comment]
Thank you, I will follow the document :)
