### ISSUE TITLE
Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/ShopApiPlugin#661]
Hi , 

I'm try to run the **shop-api** in my postmen. In the first time I'm getting the bellow error
`Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.`

_This error occurred when we have more than one channel for that when we are using the web view we can set default which channel should we use.. can you please help me to set it in **shop-api**_ 

please refer the attachments for more details

**(This is how my postmen request goes)**

<img width="1143" alt="Screen Shot 2020-07-03 at 10 21 50 AM" src="https://user-images.githubusercontent.com/20614311/86432995-16a48680-bd17-11ea-9634-ff06fa81adfd.png">

**(There are three channels in my project )**

<img width="408" alt="Screen Shot 2020-07-03 at 10 21 15 AM" src="https://user-images.githubusercontent.com/20614311/86432988-13a99600-bd17-11ea-956b-43401e9ca2ba.png">

Thank you..

**Comment by mamazu** [comment]
Can you try `localhost:8000`?

Sylius is matching the hostname and "127.0.0.1" does not match "localhost"

**Comment by kaushi5054** [comment]
Thanks @mamazu , I just tried it and now above error not occurred But when I use the `localhost` it changed as  `http://localhost:8000/en` automatically then error shows 

`No route found for "GET /en/shop-api/product-latest"`

<img width="1139" alt="Screen Shot 2020-07-03 at 4 50 55 PM" src="https://user-images.githubusercontent.com/20614311/86464604-73bb2f00-bd4d-11ea-97c8-933bca6285a1.png">

**Comment by mamazu** [comment]
The route you are looking for is `/shop-api/product-latest`

**Comment by kaushi5054** [comment]
Yes, I was trying a GET url right now, But @mamazu  even POST url I'm getting same replacement , Tried only two 
1. `shop-api//carts `
2. `/shop-api/product-latest/`

**Comment by mamazu** [comment]
If you have console access to the project you can run the command `bin/console debug:router`. This will list all available routes.

**Comment by kaushi5054** [comment]
Yes I have still I'm trying those things in my local and once I run the command . It shows like this all the shop-apis are allowed.


<img width="1025" alt="Screen Shot 2020-07-04 at 10 00 15 PM" src="https://user-images.githubusercontent.com/20614311/86516885-0dfc9f00-be42-11ea-81df-3d73335b3d35.png">

after it runs new error showing (`Unable to find template "" (looked into: /Applications/MAMP/htdocs/php/arimac-ecommerce/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /Applications/MAMP/htdocs/php/arimac-ecommerce/templates, /Applications/MAMP/htdocs/php/arimac-ecommerce/templates, /Applications/MAMP/htdocs/php/arimac-ecommerce/vendor/symfony/twig-bridge/Resources/views/Form)`) like below :( :( and  `/en/` is not going to bind with the URL (EX:- `http://localhost:8000/shop-api/product-latest`) like last time 

Did I do something wrong?

**Comment by mamazu** [comment]
What exactly are you trying to achieve? If you want to call a get route with a specific locale you have to add the `?_locale=en` attribute to it. Then it will switch the locale. The post endpoints are locale independent because for adding products to the cart you need to know the code of the product (which is locale independent).

**Comment by kaushi5054** [comment]
my office planning to share those with FE before sharing it I'm just trying to run all the endpoint via the postmen. This is the API [doc](https://app.swaggerhub.com/apis/Sylius/sylius-shop-api/1.0.0#/)  that I'm using and in that doc they haven't mention about  `?_locale=en` dependency in GET /POST methods :(

**Comment by mamazu** [comment]
Yes, because as far as I know this isn't handled by us but rather by Sylius and Symfony itself. And adding this to every endpoint sounds tedious. You can also leave the locale out then it will just use the default locale of the application (which should be en_US).

**Comment by kaushi5054** [comment]
Thank you @mamazu it's my bad that I have missed it.. I correct the URL now according to the guide my URL goes like this `http://localhost:8000/shop-api/product-latest?locale=en_US&limit=10` 

<img width="840" alt="Screen Shot 2020-07-06 at 9 10 07 AM" src="https://user-images.githubusercontent.com/20614311/86553570-cc1a4880-bf68-11ea-942e-137bcc31716f.png">


but I'm getting a error like bellow

<img width="1141" alt="Screen Shot 2020-07-06 at 9 00 32 AM" src="https://user-images.githubusercontent.com/20614311/86553811-637f9b80-bf69-11ea-81a7-2fd1203f8578.png">

Can you please guide me on it

**Comment by kaushi5054** [comment]
Found the solution it because the **priority** of the rule in **fos_rest** ( `config/packages/fos_rest.yaml` )

<img width="1123" alt="Screen Shot 2020-07-06 at 3 29 44 PM" src="https://user-images.githubusercontent.com/20614311/86581386-a9eeed80-bf9d-11ea-834b-665c30d1a4c8.png">

After that clean the cash and run the curl again.

Thank you!! :) :) :)

**Comment by mamazu** [comment]
Oh, that was easy. Glad to have helped. :D
