### ISSUE TITLE
[Bug] Mistype in validators file names

### ISSUE THREAD

**Issue by diimpp** [Sylius/ShopApiPlugin#664]
> https://github.com/Sylius/ShopApiPlugin/blob/master/src/Resources/config/validation/cart/PutOptionBasedConfigutableItemToCartRequest.xml
> https://github.com/Sylius/ShopApiPlugin/blob/master/src/Resources/config/validation/cart/PutVariantBasedConfigutableItemToCartRequest.xml

```patch
--- PutOptionBasedConfigutableItemToCartRequest.xml
+++ PutOptionBasedConfigurableItemToCartRequest.xml
--- PutVariantBasedConfigutableItemToCartRequest.xml
+++ PutVariantBasedConfigurableItemToCartRequest.xml
```

**Comment by mamazu** [comment]
Could you please create a pull request for that? If it is also an issue for 1.0 then use this tag as a base.

**Comment by mamazu** [comment]
Done and merged.
