### ISSUE TITLE
[Bug] CartReadyForCheckoutValidator checks against order state, not order checkout state

### ISSUE THREAD

**Issue by diimpp** [Sylius/ShopApiPlugin#665]
https://github.com/Sylius/ShopApiPlugin/blob/3ace12724f53c330d6b894fe2bbe639ecc140d76/src/Validator/Cart/CartReadyForCheckoutValidator.php#L47

**Comment by mamazu** [comment]
You are correct but why didn't I notice that in the tests? I will have to dig into that.
