### ISSUE TITLE
[HELP] contains unsupported keys for sylius_shop_api : request_classes

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/ShopApiPlugin#668]
Hi All,

I was fallowing the document.  As the very first stope I'm going to extend the **_/shop-api/carts/{token}/coupon_** API, 
According to doc I have to do the changers in **sylius_shop_api.yml** like bellow

```
sylius_shop_api:
    request_classes:
        add_coupon: \AddLocalizedCouponRequest
```

once I did it , I;m getting 500 error like bellow

```
{
    "code": 500,
    "message": "The routing file \"/Applications/MAMP/htdocs/php/ecommerce/config/routes/sylius_shop_api.yaml\" contains unsupported keys for \"sylius_shop_api\": \"request_classes\". Expected one of: \"resource\", \"type\", \"prefix\", \"path\", \"host\", \"schemes\", \"methods\", \"defaults\", \"requirements\", \"options\", \"condition\", \"controller\", \"name_prefix\", \"trailing_slash_on_root\", \"locale\", \"format\", \"utf8\", \"exclude\" in /Applications/MAMP/htdocs/php/ecommerce/config/routes/sylius_shop_api.yaml (which is loaded in resource \"/Applications/MAMP/htdocs/php/ecommerce/config/routes/sylius_shop_api.yaml\")."
}
```

Please guide me to resolve this.. Thank you!!

**Comment by mamazu** [comment]
The error seems to be that you changed the wrong file. The file you changed seems to be a routing file (eg. somewhere under `config/routing`)

The file you should change is in the `config/packages` directory.

**Comment by kaushi5054** [comment]
Hi mamas,
Thank you for your help, I was little bit confusing bcz of the documentation didn't carry the places of the document.

Thank you

**Comment by mamazu** [comment]
Thank you for the input we will add that to the documentation.
