### ISSUE TITLE
[HELP] Unrecognized option "total" under "sylius_shop_api.view_classes". Did you mean "totals"?

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/ShopApiPlugin#669]
Hi All,

I need a little help, in **sylius_shop_api.yml** file I did the change like bellow 
```
sylius_shop_api:
    view_classes:
        total: \NiceTotalView
```

Once I change it like this error aper and asking  **`Unrecognized option "total" under "sylius_shop_api.view_classes". Did you mean "totals"? `**  Plus guide me the correct path to resole this

Thank you

**Comment by mamazu** [comment]
The key you are looking at should be named totals not total in the last line.
