### ISSUE TITLE
[HELP] - Choosing a cart shipping method Endpoint - From where can we find the order ID of the current order? Is there any specific endpoint should we need to tryout to get the order ID ?

### ISSUE THREAD

**Issue by hasithaarimac** [Sylius/ShopApiPlugin#674]
Guys, I need a little help from you. Currently, I need to set a shipping method for my order. For that, I executed the first 3 endpoints of the Checkout flow in a sequence way and Those were succeeded. But for the 4th endpoint, there is a required parameter called "ID" in the payload (as per my understanding it asks for an order ID). So from where can we find the order ID of the current order? Is there any specific endpoint should we need to try out to get the order ID? Please help me to get a solution for this. Thank you

![image](https://user-images.githubusercontent.com/72065453/94524412-3123c880-0250-11eb-97e1-1e46c2fc534b.png)

Endpoint : Choosing a cart shipping method endpoint (/checkout/:token/shipping/:id)

**Comment by mamazu** [comment]
Hello thanks for reporting the issue. We definitely need to revise the documentation for that.

The id you are looking for is the Id of the shipping method. This can be aquired by using the GET `/checkout/{token}/shipping` endpoint.

**Comment by hasithaarimac** [comment]
Hi mamazu,

Thank you for the quick response. As per the "GET /checkout/{token}/shipping" endpoint response, there is no ID for a shipping method. It has only code and a name. So I tried out the "Choosing a cart shipping method" using the shipment method code but still I'm getting the same response from the server. Please check the below response from the server, 

**Response message**

`{
    "code": 500,
    "message": "Can not find shipment with given identifier."
}`


**Response - GET /checkout/{token}/shipping Endpoint**

`{
    "shipments": [
        {
            "methods": {
                "shippingMethod": {
                    "code": "shippingMethod",
                    "name": "shippingMethod",
                    "price": {
                        "current": 10000,
                        "currency": "USD"
                    }
                }
            }
        }
    ]
}`


Also, we're sending the shipping method again in the request body too. Please check the attached screenshots.

![image](https://user-images.githubusercontent.com/72065453/94532144-1dca2a80-025b-11eb-8d25-bb45cb7a890b.png)

**Comment by devel-pa** [comment]
Hi,

Same with payment method.
Best,

Paul

**Comment by mamazu** [comment]
The response of the get endpoint is correct. It looks like you only have one shipping method set up so if you want to use it you need the "id" to be `0`. The id (which is usually short for identifier) is in this case the index in the response.

**Comment by hasithaarimac** [comment]
Hi Mamazu,

Thanks for the response again. We tried with the position code of the shipping method and still getting the same issue.

{ "code": 500, "message": "Can not find shipment with given identifier." }

Actually, there are 5 shipping methods available (Check the below postman screenshot). The "position ID" of the selected method is "3". 

**Please find the below curl of the request.** 

```
curl --location --request PUT 'http://{host}/shop-api/checkout/b56ceb12-969c-4c53-aa08-65ab6821580e/shipping/3' \
--header 'Content-Type: application/json' \
--data-raw '{
    "method": "shippingMethod"
}'
```

**Please find the below screenshots of the admin panel and the request body as well.**

![image](https://user-images.githubusercontent.com/72065453/94643806-41e24600-0305-11eb-91f8-3f67c01f309d.png)

![image](https://user-images.githubusercontent.com/72065453/94643847-5b838d80-0305-11eb-8ff7-74b7e07553b4.png)

![image](https://user-images.githubusercontent.com/72065453/94643908-82da5a80-0305-11eb-8e4b-effa8dad39ee.png)

![image](https://user-images.githubusercontent.com/72065453/94643936-91c10d00-0305-11eb-9e54-b4680d8c2d62.png)

**Comment by mamazu** [comment]
Can you have a look at the logs and provide a stack trace on where this error is happening?

**Comment by diimpp** [comment]
@hasithaarimac you're using wrong index. Over here index is a position of `shipment` element in the cart-summary json output. Usually it will be `0` and it's not related to shipping method in the admin panel. 

If it still doesn't work, I gather from your other ticket, that you have `shipping_skipped` state and no shipments in your cart, then this is your issue and you need to fix it first.

**Comment by hasithaarimac** [comment]
@diimpp  @mamazu Thanks for the valuable inputs. Seems like I used the wrong index to add the shipping method to the cart. Now it works well. Thanks for the help guys. cheers!
