### ISSUE TITLE
Additional endpoints are missing

### ISSUE THREAD

**Issue by FDiskas** [Sylius/ShopApiPlugin#696]
I would like to get a endpoint for getting a store or stores metadata. Like the name keywords, description and so on for SPA projects

**Comment by mamazu** [comment]
What exactly do you mean with "store"? If you are referring to the Sylius channels then you might want to have a look at the admin api there you can get information on the channel: https://docs.sylius.com/en/latest/api/admin_api/channels.html

Or better still if you are using a modern version of Sylius have a look at the api platform component: https://demo.sylius.com/new-api/
