### ISSUE TITLE
Allow country and post code on billing and shipping address to be null 

### ISSUE THREAD

**Issue by NenadStef** [Sylius/ShopApiPlugin#699]
@lchrusciel I have a question about country and post code on billing and shipping address. I was looking at https://github.com/Sylius/ShopApiPlugin/issues/588 while I was truing to find a way how can I set country and post code to be nullable and now I am wondering was the idea for country and post code from the start to be mandatory or is there a way to make them nullable. If you have any suggestion on how to handle this any kind of help will be more than welcome.

**Comment by mamazu** [comment]
If I may help yo with this. The postcode shouldn't be strictly required for the checkout process but the country defnitely is. The reason for that is that depending on the country (or to be more specific, the zone) you get different shipping methods. So making the country optional would need a bigger change in the Sylius structure.

**Comment by lchrusciel** [comment]
As @mamazu said, country is a must by design. Postcodes perhaps should be skipped

**Comment by NenadStef** [comment]
@lchrusciel @mamazu Thanks for the clarification, we will probably make them mandatory.
