### ISSUE TITLE
Invalid address exists validation in case when address do not belongs to any customer

### ISSUE THREAD

**Issue by hurricane-voronin** [Sylius/ShopApiPlugin#705]
Hi there, 
I've got an error during validation of address existence in case when it does not belong to any customer:
see `AddressExistsValidator`
```php
if ($address->getCustomer()->getEmail() !== $user->getEmail()) {
    return $this->context->addViolation($constraint->message);
}
```

**Comment by mamazu** [comment]
Shouldn't this be fixed by your merge request? If not could you elaborate on what is still not working?
