### ISSUE TITLE
Changing the localeSetter Priority breaks translation in the admin panel

### ISSUE THREAD

**Issue by bindermuehle** [Sylius/ShopApiPlugin#709]
https://github.com/Sylius/ShopApiPlugin/pull/703/commits/7b0494a5f09b5473276114fc4a744bd78719dc30

Localization of the admin panel stops working when the priority of RequestLocaleSetter (25) is set higher than the Firewall (8). The firewall sets the security token which is required to get the users locale.

**Comment by mamazu** [comment]
Which version of Sylius do you use?

**Comment by lchrusciel** [comment]
This PR should fix the original issue on Sylius: https://github.com/Sylius/Sylius/pull/12458. Once the Sylius/Sylius will be released, we are ready to fix it here

**Comment by lchrusciel** [comment]
Hey @bindermuehle. It should be fixed already
