### ISSUE TITLE
There is no extension able to load the configuration for "sylius_customer" (in "/var/www/html/vendor/sylius/shop-api-plugin/src/Resources/config/app/config.yml")

### ISSUE THREAD

**Issue by Lreus** [Sylius/ShopApiPlugin#730]
Hello,

I am starting a fresh symfony skeleton project 5.4.
After requiring with composer the sylius/shop-api-plugin and followed the documentation step 2 Extend config files:, I have got an error preventing me to go to step 3 Lexik configuration : 

There is no extension able to load the configuration for "sylius_customer" (in "/var/www/html/vendor/sylius/shop-api-plugin/src/Resources/config/app/config.yml"). Looked for namespace "sylius_customer", found ""framework", "doc  
  trine", "doctrine_migrations", "debug", "twig", "web_profiler", "twig_extra", "security", "monolog", "maker", "sensio_framework_extra", "sonata_doctrine", "sonata_form", "winzou_state_machine", "jms_serializer", "bazinga_hateoa  
  s", "swiftmailer", "sylius_theme", "fos_rest", "babdev_pagerfanta", "sylius_resource", "sylius_mailer", "sylius_grid", "sylius_fixtures", "sylius_calendar", "sylius_labs_doctrine_migrations_extra", "stof_doctrine_extensions", "  
  sonata_block", "payum", "liip_imagine", "lexik_jwt_authentication", "knp_menu", "knp_gaufrette", "api_platform", "sylius_shop_api", "white_october_pagerfanta"" in /var/www/html/vendor/sylius/shop-api-plugin/src/Resources/config  
  /app/config.yml (which is being imported from "/var/www/html/config/packages/_sylius_shop_api.yaml").  
  
  This seems to be related with the config/packages/_sylius_shop_api.yaml importing configuration
  Could you help me found what I missed ?
  
  Many thanks in advance

**Comment by diimpp** [comment]
Hello @Lreus,

try starting your project with https://github.com/Sylius/Sylius-Standard and then installing this plugin.

It looks like some miss-configuration in your installation, which is impossible to debug remotely.

**Comment by Lreus** [comment]
Hi @diimpp thanks for helping,

It was indeed my big mistake not to start with Sylius/Sylius-standard.
Besides, I had the luck to rely on somebody much more experimented who told me that the api component is also part of Sylius-standard.

**Comment by mamazu** [comment]
I am a little confused should the sylius/customer package not be installed as a dependency of sylius/sylius? And `sylius/sylius` is a direct dependency of the shopapi package.

**Comment by diimpp** [comment]
Yes, it looks like most of the `sylius/sylius` is not loaded, I would guess `config/bundles.php` is not set correctly.

**Comment by mamazu** [comment]
That might be it. In the `tests/Application/config/bundles.php` there is an entry for that bundle but maybe not if just cleanly installed outside somewhere.
